[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[dependencies]
deno_core = "0.168.0"
futures = "0.3.25"
tokio = { version = "1.24.1", features = ["rt", "macros", "time"] }

[workspace]
members = [
  "mod-rs",
]
