[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.24.1", features = ["rt", "macros"] }
wasi-experimental-http-wasmtime = "0.10.0"
wasmtime = "0.35"
wasmtime-wasi = { version = "0.35", features = ["tokio"] }
